const {Schema, model} = require("mongoose");

const MapaSchema = new Schema({
    estadosActuales: [{
        codigoEmpresa: { type: String},  
        codigoEquipo: {type: String},
        abreviaturaBandera: { type: String}, 
        abreviaturaHorario: { type: String},  
        abreviaturaLinea: {type: String},
        abreviaturaPuntoDePasoDesde: { type: String}, 
        abreviaturaPuntoDePasoHasta: { type: String},  
        abreviaturaServicio: {type: String},
        alimentacion: { type: String}, 
        cargaBateria: { type: String},  
        codigoBandera: {type: String},
        codigoChofer: { type: String}, 
        codigoEstadoActual: { type: String},  
        codigoEstadoVehiculo: {type: String},
        codigoHorario: { type: String}, 
        codigoLinea: { type: String},  
        codigoMediaVueltaTeorica: {type: String},
        codigoModoTrabajoLinea: { type: String}, 
        codigoPuntoDePasoDesde: { type: String},  
        codigoPuntoDePasoHasta: {type: String},
        codigoServicio: { type: String}, 
        codigoTipoEquipo: { type: String},  
        codigoTipoVehiculo: {type: String},
        codigoVehiculo: { type: String}, 
        colorBandera: { type: String},  
        descripcionBandera: {type: String},
        descripcionEmpresa: { type: String}, 
        descripcionEstadoVehiculo: { type: String},  
        descripcionHorario: {type: String},
        descripcionLinea: { type: String}, 
        descripcionModoTrabajoLinea: { type: String},  
        descripcionPuntoDePasoDesde: {type: String},
        descripcionPuntoDePasoHasta: { type: String}, 
        descripcionServicio: { type: String},  
        descripcionTipoEquipo: {type: String},
        descripcionTipoVehiculo: { type: String}, 
        desvioHorario: { type: String},  
        distanciaAlRecorrido: {type: String},
        fechahoraFinProceso: { type: String}, 
        fechaHoraGPS: { type: String},  
        fechaHoraInicioProceso: {type: String},
        fechaHoraLlegadaMediaVueltaTeorica: { type: String}, 
        fechaHoraSalidaMediaVueltaTeorica: { type: String},  
        fechaHoraUTC: {type: String},
        identificadorChofer: { type: String}, 
        identificadorVehiculo: { type: String},  
        latitud: {type: String},
        longitud: { type: String},
        modeIndicator: { type: String},  
        odometro: {type: String},
        patente: { type: String}, 
        sentido: { type: String},  
        velocidad: {type: String},
        apellidoChofer: { type: String}, 
        nombreChofer: { type: String},  
        legajoChofer: {type: String},
        colorEstadoVehiculo: { type: String}, 
        isPrioridadVehiculo: { type: String},  
        porcentajeAvance: {type: String},
        fechaHoraProximoPuntoDePaso: { type: String}, 
        codigoPuntoDePasoDesdeProgramado: { type: String},  
        codigoPuntoDePasoHastaProgramado: {type: String},
        abreviaturaPuntoDePasoDesdeProgramado: { type: String}, 
        abreviaturaPuntoDePasoHastaProgramado: { type: String},  
        descripcionPuntoDePasoDesdeProgramado: {type: String},
        descripcionPuntoDePasoHastaProgramado: { type: String}, 
        porcentajeAvanceProgramado: { type: String},  
    }]
}, {
    timestamps: true,
    versionKey: false
})

module.exports = model('Mapa', MapaSchema)